// authActions
export const GET_ERRORS = "GET_ERRORS";
export const INDICATE_NO_ERRORS = "INDICATE_NO_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
