// authActions
export const GET_ERRORS = "GET_ERRORS";
export const INDICATE_NO_ERRORS = "INDICATE_NO_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER = "GET_USER";
export const UPDATE_ADDICS = "UPDATE_ADDICS";
export const UPDATE_ADDICPIN = "UPDATE_ADDICPIN";
export const GET_PIND = "GET_PIND";

export const CREATE_ADDIC = "CREATE_ADDIC";
export const DELETE_ADDIC = "DELETE_ADDIC";
export const EDIT_ADDIC = "EDIT_ADDIC";
export const GET_ADDICS = "GET_ADDICS";
export const LIKE_ADDIC = "LIKE_ADDIC";
export const UPDATE_ADDIC_LIKES = "UPDATE_ADDIC_LIKES";
export const UPDATE_TIMESTAMP = "UPDATE_TIMESTAMP";
export const UPDATE_CARDCOLOR = "UPDATE_CARDCOLOR";
export const GET_ADDIC = "GET_ADDIC";

export const ADD_COMMENT = "ADD_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";

export const ADD_COMMENT_THREAD = "ADD_COMMENT_THREAD";
export const DELETE_COMMENT_THREAD = "DELETE_COMMENT_THREAD";
export const EDIT_COMMENT_THREAD = "EDIT_COMMENT_THREAD";
export const GET_THREADS = "GET_THREADS";
export const CREATE_THREAD = "CREATE_THREAD";
export const EDIT_THREAD = "EDIT_THREAD";
export const DELETE_THREAD = "DELETE_THREAD";
export const GET_THREAD = "GET_THREAD";
